### ISSUE TITLE
Source SCSS on devtools

### ISSUE THREAD

**Issue by fainemesquita** [htmlstreamofficial/stream-ui-kit#5]
Is there any further documentation on how to set up the Gulp file to generate SCSS source maps? My dev tools are rendering the global and bootstrap.min CSS files only atm.

**Comment by jahaganiev** [comment]
Hi @fainemesquita, thank you for your message. In order to generate the source map you have to add a few lines of setup codes inside the gulp file but do not worry it's easy to add. Here is a link https://www.npmjs.com/package/gulp-sass for more detailed information. We will add the source maps in our coming update v1.1 Stream UI Kit soon.
